class_name ChipTray
extends RefCounted
## Holds the suit chips generated by spins until they are slotted into
## abilities or discarded at the end of the assignment phase.

var _chips: Dictionary = {}


func snapshot() -> Dictionary:
	return _chips.duplicate()


func restore(snap: Dictionary) -> void:
	_chips = snap.duplicate()


func count(suit: StringName) -> int:
	return _chips.get(suit, 0)


func total() -> int:
	var sum := 0
	for suit: StringName in _chips:
		sum += _chips[suit]
	return sum


func add(suit: StringName, amount: int) -> void:
	_chips[suit] = count(suit) + amount


func add_payout(payout: Dictionary) -> void:
	for suit: StringName in payout:
		add(suit, payout[suit])


## Removes chips of a suit. Returns false (and removes nothing) when short.
func take(suit: StringName, amount: int) -> bool:
	if count(suit) < amount:
		return false
	_chips[suit] = count(suit) - amount
	return true


## Converts chips from one suit to another (Ace's color manipulation).
func convert(from_suit: StringName, to_suit: StringName, amount: int) -> bool:
	if not take(from_suit, amount):
		return false
	add(to_suit, amount)
	return true


func discard_all() -> void:
	_chips.clear()
