extends GutTest
## ChipTray: holds the chips generated by spins until they are slotted or discarded.

const S := &"spade"
const H := &"heart"


func test_starts_empty() -> void:
	var tray := ChipTray.new()
	assert_eq(tray.total(), 0)
	assert_eq(tray.count(S), 0)


func test_add_from_payout_dictionary() -> void:
	var tray := ChipTray.new()
	tray.add_payout({S: 3, H: 1})
	assert_eq(tray.count(S), 3)
	assert_eq(tray.count(H), 1)
	assert_eq(tray.total(), 4)


func test_take_removes_chips_and_reports_success() -> void:
	var tray := ChipTray.new()
	tray.add(S, 2)
	assert_true(tray.take(S, 1))
	assert_eq(tray.count(S), 1)


func test_take_fails_without_enough_chips() -> void:
	var tray := ChipTray.new()
	tray.add(S, 1)
	assert_false(tray.take(S, 2))
	assert_eq(tray.count(S), 1)


func test_convert_changes_suit_of_existing_chips() -> void:
	var tray := ChipTray.new()
	tray.add(H, 3)
	assert_true(tray.convert(H, S, 2))
	assert_eq(tray.count(S), 2)
	assert_eq(tray.count(H), 1)


func test_discard_all_empties_the_tray() -> void:
	var tray := ChipTray.new()
	tray.add_payout({S: 5, H: 2})
	tray.discard_all()
	assert_eq(tray.total(), 0)
